"""Criação das tabelas iniciais

Revision ID: 75885d6ae26a
Revises: 
Create Date: 2026-02-01 00:15:21.911705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75885d6ae26a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('duracao', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('diretor', sa.String(length=100), nullable=False),
    sa.Column('elenco', sa.Text(), nullable=True),
    sa.Column('sinopse', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('avaliacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'filme_id', name='unique_usuario_filme_avaliacao')
    )
    op.create_table('usuario_filmes_assistidos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'filme_id')
    )
    op.create_table('usuario_filmes_em_espera',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'filme_id')
    )
    op.create_table('usuario_filmes_favoritos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('filme_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['filme_id'], ['filmes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'filme_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_filmes_favoritos')
    op.drop_table('usuario_filmes_em_espera')
    op.drop_table('usuario_filmes_assistidos')
    op.drop_table('avaliacoes')
    op.drop_table('usuarios')
    op.drop_table('filmes')
    # ### end Alembic commands ###
